### ISSUE TITLE
RequestRejectedException: No exit code delimiter found in 

### ISSUE THREAD

**Issue by realdadfish** [Malinskiy/adam#91]
**Describe the bug**
More recently `UninstallRemotePackageRequest` calls seem to fail sporadic on devices connected via network with the following exception:

```
com.malinskiy.adam.exception.RequestRejectedException: No exit code delimiter found in 
	at app//com.malinskiy.adam.request.shell.v1.ShellResultResponseTransformer.transform(ShellResultResponseTransformer.kt:35)
	at app//com.malinskiy.adam.request.shell.v1.SyncShellCommandRequest.transform(SyncShellCommandRequest.kt:37)
	at app//com.malinskiy.adam.request.SynchronousRequest.readElement$suspendImpl(SynchronousRequest.kt:43)
	at app//com.malinskiy.adam.request.SynchronousRequest$readElement$1.invokeSuspend(SynchronousRequest.kt)
	at app//kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at app//kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at app//kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:279)
	at app//kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at app//kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at app//kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at app//kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at app//kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
```

**Android device (please complete the following information):**
 - Device: Samsung A52
 - OS: Android 12
 - Adam Version 0.4.5
 - Android Debug Bridge version 1.0.41
Version 33.0.3-8952118
Installed as /opt/android-sdk/platform-tools/adb

**Comment by Malinskiy** [comment]
If you're using Android 12 then it likely has support for shell v2. Try using a newer request

Note: shell v1 uses a trick with `echo $?` to later parse the exit code after using the command. what you're seeing can be a result of sporadic socket termination between adam and adb server or adb server and the actual device.

to verify if it's really a socket problem I'd suggest using tcpdump/wireshark to intercept the traffic and double check the you see RST. If the response contains proper exit code then I'd like to have a reference stdout response to create a test for this case

**Comment by realdadfish** [comment]
Ok, will try shell_v2 then - I was wondering, there are no pre-built requests for that, right? All the predefined requests still seem to be hardcoded / derived from the v1 implementation.

**Comment by Malinskiy** [comment]
Ideally the requests would use delegation to shell dynamically, but unfortunately thats not the case yet

**Comment by realdadfish** [comment]
I guess something is generally wrong with the device farm we're connecting to, shellv2 does not work either:

```
java.lang.AssertionError: Expected 1 bytes, received 0
    at com.malinskiy.adam.transport.vertx.VertxSocket.readFully(VertxSocket.kt:132)
    at com.malinskiy.adam.transport.vertx.VertxSocket$readFully$1.invokeSuspend(VertxSocket.kt)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
    at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
    at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
    at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
    at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
    at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
```

**Comment by Malinskiy** [comment]
I'd check tcpdump of the connection and analyse the TCP closing part. Normally this should be FIN -> ACK, FIN -> ACK but maybe something is terminating the socket earlier. It might give you some clues.
